apply plugin: 'com.android.application'

android {
    defaultConfig {
        applicationId "org.tatarkeyboard.ime"
        compileSdk 37
        minSdkVersion 24
        targetSdkVersion 37
        versionCode 1
        versionName "0.1.0"
    }
    buildTypes {
        debug {
            applicationIdSuffix ".debug"
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'rkr.simplekeyboard.inputmethod'
}

dependencies {
}
